"""refactor: adds lat/lon in Locale model

Revision ID: 81a91de431ad
Revises: 755b8ce64a63
Create Date: 2020-05-11 10:28:07.017419

"""
from sqlalchemy.engine.result import ResultProxy
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '81a91de431ad'
down_revision = '755b8ce64a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locales', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('locales', sa.Column('lon', sa.Float(), nullable=True))
    # ### end Alembic commands ###

    bind = op.get_bind()
    meta = sa.MetaData(bind)
    Locale = sa.Table('locales', meta, autoload=True)
    Country = sa.Table('countries', meta, autoload=True)

    # Update Locale
    locales = [
        {'name': 'Afghanistan', 'lat': '33.0', 'lon': '65.0'},
        {'name': 'Albania', 'lat': '41.1533', 'lon': '20.1683'},
        {'name': 'Algeria', 'lat': '28.0339', 'lon': '1.6596'},
        {'name': 'Andorra', 'lat': '42.5063', 'lon': '1.5218'},
        {'name': 'Angola', 'lat': '-11.2027', 'lon': '17.8739'},
        {'name': 'Antigua and Barbuda', 'lat': '17.0608', 'lon': '-61.7964'},
        {'name': 'Argentina', 'lat': '-38.4161', 'lon': '-63.6167'},
        {'name': 'Armenia', 'lat': '40.0691', 'lon': '45.0382'},
        {'name': 'Australia', 'lat': '-35.4735', 'lon': '149.0124'},
        {'name': 'Austria', 'lat': '47.5162', 'lon': '14.5501'},
        {'name': 'Azerbaijan', 'lat': '40.1431', 'lon': '47.5769'},
        {'name': 'Bahamas', 'lat': '25.0343', 'lon': '-77.3963'},
        {'name': 'Bahrain', 'lat': '26.0275', 'lon': '50.55'},
        {'name': 'Bangladesh', 'lat': '23.685', 'lon': '90.3563'},
        {'name': 'Barbados', 'lat': '13.1939', 'lon': '-59.5432'},
        {'name': 'Belarus', 'lat': '53.7098', 'lon': '27.9534'},
        {'name': 'Belgium', 'lat': '50.8333', 'lon': '4.0'},
        {'name': 'Belize', 'lat': '13.1939', 'lon': '-59.5432'},
        {'name': 'Benin', 'lat': '9.3077', 'lon': '2.3158'},
        {'name': 'Bhutan', 'lat': '27.5142', 'lon': '90.4336'},
        {'name': 'Bolivia', 'lat': '-16.2902', 'lon': '-63.5887'},
        {'name': 'Bosnia and Herzegovina', 'lat': '43.9159', 'lon': '17.6791'},
        {'name': 'Botswana', 'lat': '-22.3285', 'lon': '24.6849'},
        {'name': 'Brazil', 'lat': '-14.235', 'lon': '-51.9253'},
        {'name': 'Brunei', 'lat': '4.5353', 'lon': '114.7277'},
        {'name': 'Bulgaria', 'lat': '42.7339', 'lon': '25.4858'},
        {'name': 'Burkina Faso', 'lat': '12.2383', 'lon': '-1.5616'},
        {'name': 'Burma', 'lat': '21.9162', 'lon': '95.956'},
        {'name': 'Burundi', 'lat': '-3.3731', 'lon': '29.9189'},
        {'name': 'Cabo Verde', 'lat': '16.5388', 'lon': '-23.0418'},
        {'name': 'Cambodia', 'lat': '11.55', 'lon': '104.9167'},
        {'name': 'Cameroon', 'lat': '3.8480000000000003', 'lon': '11.5021'},
        {'name': 'Canada', 'lat': '53.9333', 'lon': '-116.5765'},
        {
            'name': 'Central African Republic',
            'lat': '6.6111',
            'lon': '20.9394',
        },
        {'name': 'Chad', 'lat': '15.4542', 'lon': '18.7322'},
        {'name': 'Chile', 'lat': '-35.6751', 'lon': '-71.543'},
        {'name': 'China', 'lat': '31.8257', 'lon': '117.2264'},
        {'name': 'Colombia', 'lat': '4.5709', 'lon': '-74.2973'},
        {'name': 'Comoros', 'lat': '-11.6455', 'lon': '43.3333'},
        {
            'name': 'Congo (Brazzaville)',
            'lat': '-4.233333',
            'lon': '15.233333',
        },
        {'name': 'Congo (Kinshasa)', 'lat': '-4.316667', 'lon': '15.316667'},
        {'name': 'Costa Rica', 'lat': '9.7489', 'lon': '-83.7534'},
        {'name': 'Cote d\'Ivoire', 'lat': '7.54', 'lon': '-5.5471'},
        {'name': 'Croatia', 'lat': '45.1', 'lon': '15.2'},
        {'name': 'Cuba', 'lat': '22.0', 'lon': '-80.0'},
        {'name': 'Cyprus', 'lat': '35.1264', 'lon': '33.4299'},
        {'name': 'Czechia', 'lat': '49.8175', 'lon': '15.472999999999999'},
        {'name': 'Denmark', 'lat': '61.8926', 'lon': '-6.9118'},
        {'name': 'Diamond Princess', 'lat': '0.0', 'lon': '0.0'},
        {'name': 'Djibouti', 'lat': '11.8251', 'lon': '42.5903'},
        {'name': 'Dominica', 'lat': '15.415', 'lon': '-61.371'},
        {'name': 'Dominican Republic', 'lat': '18.7357', 'lon': '-70.1627'},
        {'name': 'Ecuador', 'lat': '-1.8312', 'lon': '-78.1834'},
        {'name': 'Egypt', 'lat': '26.0', 'lon': '30.0'},
        {'name': 'El Salvador', 'lat': '13.7942', 'lon': '-88.8965'},
        {'name': 'Equatorial Guinea', 'lat': '1.5', 'lon': '10.0'},
        {'name': 'Eritrea', 'lat': '15.1794', 'lon': '39.7823'},
        {'name': 'Estonia', 'lat': '58.5953', 'lon': '25.0136'},
        {'name': 'Eswatini', 'lat': '-26.5225', 'lon': '31.4659'},
        {'name': 'Ethiopia', 'lat': '9.145', 'lon': '40.4897'},
        {'name': 'Fiji', 'lat': '-17.7134', 'lon': '178.065'},
        {'name': 'Finland', 'lat': '64.0', 'lon': '26.0'},
        {'name': 'France', 'lat': '3.9339', 'lon': '-53.1258'},
        {'name': 'Gabon', 'lat': '-0.8037', 'lon': '11.6094'},
        {'name': 'Gambia', 'lat': '13.4432', 'lon': '-15.3101'},
        {'name': 'Georgia', 'lat': '42.3154', 'lon': '43.3569'},
        {'name': 'Germany', 'lat': '51.0', 'lon': '9.0'},
        {'name': 'Ghana', 'lat': '7.9465', 'lon': '-1.0232'},
        {'name': 'Greece', 'lat': '39.0742', 'lon': '21.8243'},
        {'name': 'Grenada', 'lat': '12.1165', 'lon': '-61.678999999999995'},
        {'name': 'Guatemala', 'lat': '15.7835', 'lon': '-90.2308'},
        {'name': 'Guinea', 'lat': '9.9456', 'lon': '-9.6966'},
        {'name': 'Guinea-Bissau', 'lat': '11.8037', 'lon': '-15.1804'},
        {'name': 'Guyana', 'lat': '5.0', 'lon': '-58.75'},
        {'name': 'Haiti', 'lat': '18.9712', 'lon': '-72.2852'},
        {'name': 'Holy See', 'lat': '41.9029', 'lon': '12.4534'},
        {'name': 'Honduras', 'lat': '15.2', 'lon': '-86.2419'},
        {'name': 'Hungary', 'lat': '47.1625', 'lon': '19.5033'},
        {'name': 'Iceland', 'lat': '64.9631', 'lon': '-19.0208'},
        {'name': 'India', 'lat': '21.0', 'lon': '78.0'},
        {'name': 'Indonesia', 'lat': '-0.7893', 'lon': '113.9213'},
        {'name': 'Iran', 'lat': '32.0', 'lon': '53.0'},
        {'name': 'Iraq', 'lat': '33.0', 'lon': '44.0'},
        {'name': 'Ireland', 'lat': '53.1424', 'lon': '-7.6921'},
        {'name': 'Israel', 'lat': '31.0', 'lon': '35.0'},
        {'name': 'Italy', 'lat': '43.0', 'lon': '12.0'},
        {'name': 'Jamaica', 'lat': '18.1096', 'lon': '-77.2975'},
        {'name': 'Japan', 'lat': '36.0', 'lon': '138.0'},
        {'name': 'Jordan', 'lat': '31.24', 'lon': '36.51'},
        {'name': 'Kazakhstan', 'lat': '48.0196', 'lon': '66.9237'},
        {'name': 'Kenya', 'lat': '-0.0236', 'lon': '37.9062'},
        {'name': 'Kosovo', 'lat': '42.602636', 'lon': '20.902977'},
        {'name': 'Kuwait', 'lat': '29.5', 'lon': '47.75'},
        {'name': 'Kyrgyzstan', 'lat': '41.2044', 'lon': '74.7661'},
        {'name': 'Laos', 'lat': '19.856270000000002', 'lon': '102.495496'},
        {'name': 'Latvia', 'lat': '56.8796', 'lon': '24.6032'},
        {'name': 'Lebanon', 'lat': '33.8547', 'lon': '35.8623'},
        {'name': 'Lesotho', 'lat': '-29.609988', 'lon': '28.233608'},
        {'name': 'Liberia', 'lat': '6.4281', 'lon': '-9.4295'},
        {'name': 'Libya', 'lat': '26.3351', 'lon': '17.228331'},
        {'name': 'Liechtenstein', 'lat': '47.14', 'lon': '9.55'},
        {'name': 'Lithuania', 'lat': '55.1694', 'lon': '23.8813'},
        {'name': 'Luxembourg', 'lat': '49.8153', 'lon': '6.1296'},
        {'name': 'MS Zaandam', 'lat': '0.0', 'lon': '0.0'},
        {'name': 'Madagascar', 'lat': '-18.7669', 'lon': '46.8691'},
        {'name': 'Malawi', 'lat': '-13.254307999999998', 'lon': '34.301525'},
        {'name': 'Malaysia', 'lat': '2.5', 'lon': '112.5'},
        {'name': 'Maldives', 'lat': '3.2028', 'lon': '73.2207'},
        {'name': 'Mali', 'lat': '17.570692', 'lon': '-3.996166000000001'},
        {'name': 'Malta', 'lat': '35.9375', 'lon': '14.3754'},
        {'name': 'Mauritania', 'lat': '21.0079', 'lon': '10.9408'},
        {'name': 'Mauritius', 'lat': '-20.2', 'lon': '57.5'},
        {'name': 'Mexico', 'lat': '23.6345', 'lon': '-102.5528'},
        {'name': 'Moldova', 'lat': '47.4116', 'lon': '28.3699'},
        {'name': 'Monaco', 'lat': '43.7333', 'lon': '7.4167'},
        {'name': 'Mongolia', 'lat': '46.8625', 'lon': '103.8467'},
        {'name': 'Montenegro', 'lat': '42.5', 'lon': '19.3'},
        {'name': 'Morocco', 'lat': '31.7917', 'lon': '-7.0926'},
        {'name': 'Mozambique', 'lat': '-18.665695', 'lon': '35.529562'},
        {'name': 'Namibia', 'lat': '-22.9576', 'lon': '18.4904'},
        {'name': 'Nepal', 'lat': '28.1667', 'lon': '84.25'},
        {'name': 'Netherlands', 'lat': '12.5186', 'lon': '-70.0358'},
        {'name': 'New Zealand', 'lat': '-40.9006', 'lon': '174.886'},
        {'name': 'Nicaragua', 'lat': '12.8654', 'lon': '-85.2072'},
        {'name': 'Niger', 'lat': '17.6078', 'lon': '8.0817'},
        {'name': 'Nigeria', 'lat': '9.082', 'lon': '8.6753'},
        {'name': 'North Macedonia', 'lat': '41.6086', 'lon': '21.7453'},
        {'name': 'Norway', 'lat': '60.472', 'lon': '8.4689'},
        {'name': 'Oman', 'lat': '21.0', 'lon': '57.0'},
        {'name': 'Pakistan', 'lat': '30.3753', 'lon': '69.3451'},
        {'name': 'Panama', 'lat': '8.538', 'lon': '-80.7821'},
        {'name': 'Papua New Guinea', 'lat': '-6.315', 'lon': '143.9555'},
        {'name': 'Paraguay', 'lat': '-23.4425', 'lon': '-58.4438'},
        {'name': 'Peru', 'lat': '-9.19', 'lon': '-75.0152'},
        {'name': 'Philippines', 'lat': '13.0', 'lon': '122.0'},
        {'name': 'Poland', 'lat': '51.9194', 'lon': '19.1451'},
        {'name': 'Portugal', 'lat': '39.3999', 'lon': '-8.2245'},
        {'name': 'Qatar', 'lat': '25.3548', 'lon': '51.1839'},
        {'name': 'Romania', 'lat': '45.9432', 'lon': '24.9668'},
        {'name': 'Russia', 'lat': '60.0', 'lon': '90.0'},
        {'name': 'Rwanda', 'lat': '-1.9403', 'lon': '29.8739'},
        {
            'name': 'Saint Kitts and Nevis',
            'lat': '17.357822',
            'lon': '-62.782998',
        },
        {'name': 'Saint Lucia', 'lat': '13.9094', 'lon': '-60.9789'},
        {
            'name': 'Saint Vincent and the Grenadines',
            'lat': '12.9843',
            'lon': '-61.2872',
        },
        {'name': 'San Marino', 'lat': '43.9424', 'lon': '12.4578'},
        {'name': 'Sao Tome and Principe', 'lat': '0.18636', 'lon': '6.613081'},
        {'name': 'Saudi Arabia', 'lat': '24.0', 'lon': '45.0'},
        {'name': 'Senegal', 'lat': '14.4974', 'lon': '-14.4524'},
        {'name': 'Serbia', 'lat': '44.0165', 'lon': '21.0059'},
        {'name': 'Seychelles', 'lat': '-4.6796', 'lon': '55.492'},
        {
            'name': 'Sierra Leone',
            'lat': '8.460555000000001',
            'lon': '-11.779889',
        },
        {'name': 'Singapore', 'lat': '1.2833', 'lon': '103.8333'},
        {'name': 'Slovakia', 'lat': '48.669', 'lon': '19.699'},
        {'name': 'Slovenia', 'lat': '46.1512', 'lon': '14.9955'},
        {'name': 'Somalia', 'lat': '5.1521', 'lon': '46.1996'},
        {'name': 'South Africa', 'lat': '-30.5595', 'lon': '22.9375'},
        {'name': 'South Korea', 'lat': '36.0', 'lon': '128.0'},
        {'name': 'South Sudan', 'lat': '6.8770000000000024', 'lon': '31.307'},
        {'name': 'Spain', 'lat': '40.0', 'lon': '-4.0'},
        {'name': 'Sri Lanka', 'lat': '7.0', 'lon': '81.0'},
        {'name': 'Sudan', 'lat': '12.8628', 'lon': '30.2176'},
        {'name': 'Suriname', 'lat': '3.9193', 'lon': '-56.0278'},
        {'name': 'Sweden', 'lat': '63.0', 'lon': '16.0'},
        {'name': 'Switzerland', 'lat': '46.8182', 'lon': '8.2275'},
        {'name': 'Syria', 'lat': '34.802075', 'lon': '38.99681500000001'},
        {'name': 'Taiwan', 'lat': '23.7', 'lon': '121.0'},
        {
            'name': 'Tajikistan',
            'lat': '38.861034000000004',
            'lon': '71.276093',
        },
        {'name': 'Tanzania', 'lat': '-6.369', 'lon': '34.8888'},
        {'name': 'Thailand', 'lat': '15.0', 'lon': '101.0'},
        {'name': 'Timor-Leste', 'lat': '-8.874217', 'lon': '125.727539'},
        {'name': 'Togo', 'lat': '8.6195', 'lon': '0.8248'},
        {'name': 'Trinidad and Tobago', 'lat': '10.6918', 'lon': '-61.2225'},
        {'name': 'Tunisia', 'lat': '34.0', 'lon': '9.0'},
        {'name': 'Turkey', 'lat': '38.9637', 'lon': '35.2433'},
        {'name': 'Uganda', 'lat': '1.0', 'lon': '32.0'},
        {'name': 'Ukraine', 'lat': '48.3794', 'lon': '31.1656'},
        {'name': 'United Arab Emirates', 'lat': '24.0', 'lon': '54.0'},
        {'name': 'United Kingdom', 'lat': '32.3078', 'lon': '-64.7505'},
        {'name': 'United States', 'lat': '37.0902', 'lon': '-95.7129'},
        {'name': 'Uruguay', 'lat': '-32.5228', 'lon': '-55.7658'},
        {'name': 'Uzbekistan', 'lat': '41.3775', 'lon': '64.5853'},
        {'name': 'Venezuela', 'lat': '6.4238', 'lon': '-66.5897'},
        {'name': 'Vietnam', 'lat': '16.0', 'lon': '108.0'},
        {'name': 'West Bank and Gaza', 'lat': '31.9522', 'lon': '35.2332'},
        {'name': 'Western Sahara', 'lat': '24.2155', 'lon': '-12.8858'},
        {'name': 'Yemen', 'lat': '15.552726999999999', 'lon': '48.516388'},
        {'name': 'Zambia', 'lat': '-15.4167', 'lon': '28.2833'},
        {'name': 'Zimbabwe', 'lat': '-20.0', 'lon': '30.0'},
    ]

    def _search(lst: ResultProxy, val: str):
        for r in lst:
            if val == r.name:
                return r.id
        return None

    countries = bind.execute(Country.select()).fetchall()

    for l in locales:
        coyntry_id = _search(countries, l['name'])
        bind.execute(
            Locale.update()
            .where(Locale.c.country_id == coyntry_id)
            .values({'lat': l['lat'], 'lon': l['lon']})
        )
    # end update Locale


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locales', 'lon')
    op.drop_column('locales', 'lat')
    # ### end Alembic commands ###
